### ISSUE TITLE
spacemacs-rocks suggestion

### ISSUE THREAD

**Issue by LonglyCode** [zilongshanren/Spacemacs-rocks#12]
视频做的很棒，可以做一期关于files/buffers/layouts(windows)/projects管理的视频，可以提取一些共通的东西来讲。

**Comment by zilongshanren** [comment]
这个已经在计划中了，可能本周末就会讲了。

**Comment by zilongshanren** [comment]
@LonglyCode 
另外，建议可以在https://github.com/zilongshanren/Spacemacs-rocks/issues/5留言。
不用新建issue了。我先关了。

**Comment by LonglyCode** [comment]
嗯，期待中…
