### ISSUE TITLE
视频里提到的东西能不能维护一份文字版？

### ISSUE THREAD

**Issue by erstern** [zilongshanren/Spacemacs-rocks#19]
有些东西会发生改变，比如 `SPC s l` 这个快捷键在某一次升级之后就失效了。（spacemacs-rocks的README里还有）
今天我用 `SPC f e h` 的时候，提示改成 `SPC h SPC` 了。

建议加一份视频的文字说明，在看视频的时候万一没听清楚也能从文字版看到操作是什么，而且跟随更新及时作出修改，这样也方便大家了解视频发布之后 spacemacs 又有了哪些变化。

**Comment by li-xinyang** [comment]
你做呀 开源是分析不是索取

**Comment by zilongshanren** [comment]
@erstern 
这个维护成本有点大哦，建议直接看官方的文档。

**Comment by zilongshanren** [comment]
@erstern  这个issue我先关闭了 。
